services:
  gateway:
    build:
      context: ./api-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - backend-net
    depends_on:
      - postgres
      - keycloak
      - ms-gestion-calculos
      - ms-rutas-transportistas
      - ms-solicitudes
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/tpi-backend
      - SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED=false

  ms-solicitudes:
    build:
      context: ./ms-solicitudes
    container_name: ms-solicitudes
    ports:
      - "8083:8083"
    networks:
      - backend-net
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tpi_backend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/tpi-backend
      # base-urls para comunicaci√≥n entre microservicios
      - APP_TRANSPORTES_BASE_URL=http://ms-rutas-transportistas:8082
      - APP_CALCULOS_BASE_URL=http://ms-gestion-calculos:8084

  ms-gestion-calculos:
    build:
      context: ./ms-gestion-calculos
    container_name: ms-gestion-calculos
    ports:
      - "8084:8084"
    networks:
      - backend-net
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tpi_backend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/tpi-backend
      - APP_RUTAS_BASE_URL=http://ms-rutas-transportistas:8082

  ms-rutas-transportistas:
    build:
      context: ./ms-rutas-transportistas
    container_name: ms-rutas-transportistas
    ports:
      - "8082:8082"
    networks:
      - backend-net
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tpi_backend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GOOGLE_MAPS_API_URL=${GOOGLE_MAPS_API_URL:-https://maps.googleapis.com/maps/api}
      - GOOGLE_MAPS_APIKEY=${GOOGLE_MAPS_APIKEY:-}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/tpi-backend
      - APP_SOLICITUDES_BASE_URL=http://ms-solicitudes:8083
      - APP_CALCULOS_BASE_URL=http://ms-gestion-calculos:8084

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME=keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    networks:
      - backend-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpi_backend_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
