server:
  port: 8082

spring:
  application:
    name: ms-rutas-transportistas
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tpi-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger-ui.html

app:
  solicitudes:
    base-url: http://ms-solicitudes:8083
  calculos:
    base-url: http://ms-gestion-calculos:8081

